### ISSUE TITLE
trng example build failure

### ISSUE THREAD

**Issue by silabs-DenverL** [SiliconLabs/platform_applications#13]
could not pass build, report because the SL_DEVICE_INIT_LFXO_TIMEOUT is not in header file sl_device_init_lfxo_config.h:
C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.2/platform/service/device_init/src/sl_device_init_lfxo_s1.c:41:22: error: 'SL_DEVICE_INIT_LFXO_TIMEOUT' undeclared (first use in this function); did you mean 'SL_DEVICE_INIT_LFXO_MODE'?
   lfxoInit.timeout = SL_DEVICE_INIT_LFXO_TIMEOUT;

**Comment by silabs-Joe** [comment]
Hi @silabs-DenverL  The readme file indicates that this example was written for SDK version 3.1.1, and I'm able to build it that way.  Do you still see this issue if you switch SDK?

**Comment by silabs-marao** [comment]
@silabs-DenverL This example was written for GSDK v3.1.1. This example works as expected in this SDK. If you want to port it to a newer SDK version, please note that timeout was a new feature added in GSDK v3.2 and you will need to modify "sl_device_init_lfxo_config.h" file in the project under the **config** folder. You can borrow the definition from (or use this config file instead) {StudioLocation}\developer\sdks\gecko_sdk_suite\v3.2\platform\service\device_init\config\s1. 


This issue will be closed since the example builds without any issues on the SDK it was written for. Please note that these are experimental quality examples. Please refer to the [readme](https://github.com/SiliconLabs/platform_applications) here for further information.
