### ISSUE TITLE
iar project file is not written correct

### ISSUE THREAD

**Issue by silabs-DenverL** [SiliconLabs/platform_applications#8]
take the platform_pcnt_edge_counter_series1 as example,
pcnt_edge_counter.eww only include project for EFR32MG1 (EFR32MG1_pcnt_edge_counter.ewp).

platform_pg12_iadc_stimulus\iar\iadc_stimulus.ewp
          '<state>$PROJ_DIR$/../../../hardware\kit\common\bsp</state>'
          '<state>$PROJ_DIR$/../../../../../hardware\kit\common\drivers</state>'

May need to consider made change on below examples also:
platform_async_em01grpaclk_out_series2,
platform_pcnt_edge_counter_series1,
platform_pg12_iadc_stimulus,
platform_spi_flash_bandwidth,

**Comment by silabs-DenverL** [comment]
Change 
#define PCNT_PRS_CH       4
-->
#define PCNT_PRS_CH       pcntPRSCh4

**Comment by silabs-marao** [comment]
@silabs-DenverL - Please use the bug report for one unique bug at a time. I have addressed your original issue about the IAR projects in 961e4daadeb1386939f3f44ea6a1b9404d6917a9. If needed, please open another ticket to change the PRS channel definition as an enhancement (since this is not a bug). 

Please also note - Unless otherwise specified in the specific directory, all examples are considered to be EXPERIMENTAL QUALITY which implies that the code provided in the repos has not been formally tested and is provided as-is. It is not suitable for production environments. In addition, this code will not be maintained and there may be no bug maintenance planned for these resources. Silicon Labs may update projects from time to time.
